### ISSUE TITLE
Plan a Demo Day for Claim Extractions Findings

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/kosh-v2#73]
Everything is documented in this Nuclino Doc - https://app.nuclino.com/TattleRattle/Tattle-Docs/Plan-a-Demo-Day-for-Claim-Extractions-Findings-623ab60b-4828-44fc-9417-747c3dce10ce

**Comment by tarunima** [comment]
@dennyabrain to review.

**Comment by dennyabrain** [comment]
Like the progress so far on the planning document. We've coordinated the date and time (29th Friday 9 pm) for it with everyone and a calendar invite has been sent out as well.
Next week, aatman will work on putting together the slides and coordinating with swair for his slides. We will do a rehearsal before the actual demo day. 
We also have to ensure the talk is recorded.
