### ISSUE TITLE
Curate PPT for Demo Day

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/kosh-v2#74]
- [x] Create the PPT on Pitch
- [x] Try to add the annotated roboflow image for YOLO
- [x] Add gemini OCR too
- [x] test KOSMOS-2 - https://huggingface.co/docs/transformers/main/model_doc/kosmos-2

**Comment by dennyabrain** [comment]
- Send reminders today
- Dry run tomorrow morning
